# Configuration for personal vault snapshot with similarity search
vaultPath: /Users/danielseltzer/Notes/Personal-sync-250710
indexPath: /Users/danielseltzer/code/mmt/.index-personal

# Enable file watching for automatic updates
fileWatching:
  enabled: true
  debounceMs: 200

# Similarity search configuration
similarity:
  enabled: true
  ollamaUrl: http://localhost:11434
  model: nomic-embed-text

# Required port settings
apiPort: 3001
webPort: 5173