# Configuration for personal vault snapshot
vaults:
  - name: 'Personal'
    path: /Users/danielseltzer/Notes/Personal-sync-250710
    indexPath: /Users/danielseltzer/code/mmt/.index-personal
    # Enable file watching for automatic updates
    fileWatching:
      enabled: true
      debounceMs: 200

# Required port settings
apiPort: 3001
webPort: 5173