version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: mmt-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port (optional)
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s