# Configuration for personal vault with Qdrant similarity search
vaults:
  - name: 'Personal'
    path: /Users/danielseltzer/Notes/Personal-sync-250813
    indexPath: /Users/danielseltzer/code/mmt/.index-personal
    # Enable file watching for automatic updates
    fileWatching:
      enabled: true
      debounceMs: 200
    # Per-vault similarity configuration
    similarity:
      enabled: true
      provider: qdrant
      model: nomic-embed-text
      qdrant:
        collectionName: personal-documents
        onDisk: false
      # New component-based network configuration
      network:
        host: localhost
        ports:
          ollama: 11434
          qdrant: 6333
        protocol: http

  # InData Bizdev
  - name: 'InD BizDev'
    path: /Users/danielseltzer/Notes/ind-bizdev-250813
    indexPath: /Users/danielseltzer/code/mmt/.index/ind-bizdev
    fileWatching:
      enabled: true
      debounceMs: 500
    # Per-vault similarity configuration
    similarity:
      enabled: true
      provider: qdrant
      model: nomic-embed-text
      qdrant:
        collectionName: ind-bizdev-documents
        onDisk: false
      # New component-based network configuration
      network:
        host: localhost
        ports:
          ollama: 11434
          qdrant: 6333
        protocol: http
  
  # InData Work
  - name: 'Work'
    path: /Users/danielseltzer/Notes/Work-sync-250813
    indexPath: /Users/danielseltzer/code/mmt/.index/work
    fileWatching:
      enabled: true
      debounceMs: 500
    # Per-vault similarity configuration
    similarity:
      enabled: true
      provider: qdrant
      model: nomic-embed-text
      qdrant:
        collectionName: work-documents
        onDisk: false
      # New component-based network configuration
      network:
        host: localhost
        ports:
          ollama: 11434
          qdrant: 6333
        protocol: http

# Required port settings
apiPort: 3001
webPort: 5173

# Global network configuration (can be overridden per-vault)
network:
  host: localhost
  ports:
    ollama: 11434
    qdrant: 6333
  protocol: http