# Configuration for personal vault with Qdrant similarity search
vaults:
  - name: 'Personal'
    path: /Users/danielseltzer/Notes/Personal-sync-250813
    indexPath: /Users/danielseltzer/code/mmt/.index-personal
    # Enable file watching for automatic updates
    fileWatching:
      enabled: true
      debounceMs: 200
    # Per-vault similarity configuration
    similarity:
      enabled: true
      provider: qdrant
      ollamaUrl: http://localhost:11434
      model: nomic-embed-text
      qdrant:
        url: http://localhost:6333
        collectionName: personal-documents
        onDisk: false

  # InData Bizdev
  - name: 'InD BizDev'
    path: /Users/danielseltzer/Notes/ind-bizdev-250813
    indexPath: /Users/danielseltzer/code/mmt/.index/ind-bizdev
    fileWatching:
      enabled: true
      debounceMs: 500
    # Per-vault similarity configuration
    similarity:
      enabled: true
      provider: qdrant
      ollamaUrl: http://localhost:11434
      model: nomic-embed-text
      qdrant:
        url: http://localhost:6333
        collectionName: ind-bizdev-documents
        onDisk: false
  
  # InData Work
  - name: 'Work'
    path: /Users/danielseltzer/Notes/Work-sync-250813
    indexPath: /Users/danielseltzer/code/mmt/.index/work
    fileWatching:
      enabled: true
      debounceMs: 500
    # Per-vault similarity configuration
    similarity:
      enabled: true
      provider: qdrant
      ollamaUrl: http://localhost:11434
      model: nomic-embed-text
      qdrant:
        url: http://localhost:6333
        collectionName: work-documents
        onDisk: false

# Required port settings
apiPort: 3001
webPort: 5173

# Global similarity configuration (deprecated - now per-vault)
# similarity:
#   enabled: true
#   provider: qdrant
#   ollamaUrl: http://localhost:11434
#   model: nomic-embed-text
#
#   qdrant:
#     url: http://localhost:6333
#     collectionName: personal-documents
#     onDisk: false