# Test Configuration for MMT
# This configuration is used for running tests

vaultPath: /tmp/mmt-test-vault
indexPath: /tmp/mmt-test-index

# API Server Configuration
apiPort: 3001

# File watching disabled for tests
fileWatching:
  enabled: false