# Test configuration for validating indexer against production vault
# Update the vaultPath to point to your actual Obsidian vault

vaultPath: /Users/danielseltzer/Documents/ObsidianVault  # UPDATE THIS PATH
indexPath: .mmt-data/indexes/test
apiPort: 3001
webPort: 5173

# Optional settings
cache:
  enabled: true
  location: .mmt-data/cache

performance:
  maxConcurrent: 4
  useWorkers: true

logs:
  directory: .mmt-data/logs
  level: info