# Example MMT configuration file
# 
# All paths must be absolute. No defaults are provided.
# The vault directory must exist at load time.
# The index path will be created by the indexer if it doesn't exist.

# Absolute path to your markdown vault directory
vaultPath: /Users/username/Documents/my-notes

# Absolute path where MMT will store its index database
indexPath: /Users/username/.mmt/my-notes-index

# Port for the API server (required, no defaults)
apiPort: 3001

# Port for the web server (required, no defaults)
webPort: 5173

# Optional: File watching configuration for automatic index updates
# Uncomment to enable real-time synchronization when files change
# fileWatching:
#   enabled: true              # Enable automatic index updates
#   debounceMs: 100           # Milliseconds to wait before processing rapid changes
#   ignorePatterns:           # Glob patterns for files/directories to ignore
#     - .git/**
#     - .obsidian/**
#     - .trash/**
#     - node_modules/**