# Configuration for personal vault snapshot with similarity search
vaults:
  - name: Personal
    path: /Users/danielseltzer/Notes/Personal-sync
    indexPath: /Users/danielseltzer/code/mmt/.index-personal
    # Enable file watching for automatic updates
    fileWatching:
      enabled: true
      debounceMs: 200

# Similarity search configuration
similarity:
  enabled: true
  provider: qdrant
  qdrantUrl: http://localhost:6333
  ollamaUrl: http://localhost:11434
  model: nomic-embed-text

# Required port settings
apiPort: 3001
webPort: 5173